### ISSUE TITLE
Task3 

### ISSUE THREAD

**Issue by eugeniipol** [eugeniipol/uni-train#3]
@slawiko Здравствуйте, я вроде вмержил PR, сделал тэг, теперь можно комментарий по работе?

**Comment by slawiko** [comment]
Да, мы видели что вмержили PR. К сожалению не было времени проверить. 

Вы сделали тэг, но не запушили его :) скорее всего не выполнили команду `git push origin master --tags`.

Очень много файлов в одной папке, глаза разбегаются. Правильно было бы их рассортировать: картинки, стили, ...

У меня дизайн совсем рассыпался:
<img width="1680" alt="2018-03-01 22 17 34" src="https://user-images.githubusercontent.com/10272192/36864683-660b7050-1d9e-11e8-8fb8-5bb01b9baf3c.png">
Очень большие отступы между постами, неудобно смотреть. Не понятно где какой фильтр.

HTML:
- класс `.knopka` - плохое название. Если возникают проблемы с переводом на английский язык, не стесняйтесь пользоваться переводчиком.

CSS:
- отрицательные значения для `margin`, `top` и так далее - плохая практика. Если у вас возникает необходимость так писать, значит у вас ошибка в верстке.
- "попиксельные" значения - также плохая практика. Размер 34 или 40 px не сделает погоды, скорее всего.
- классы `list2`, `list3` тяжелы для восприятия. Не понятно что они из себя представляют.
- можно не писать `div.className`, а заменять на `.className`. Так принято
- `filterbar` плохое название класса. Принято писать через `-`, то есть `.filter-bar` например.

**Comment by eugeniipol** [comment]
@slawiko спасибо, поработаю над этим всем. Может можно какой-нибудь совет по респонсив интерфейсу, пропорции экранов же везде разные, даже в процентах устанавливая взаиморасположение, не очень получается?

**Comment by eugeniipol** [comment]
@slawiko Вроде всё поправил, фильтры теперь не должны смещаться, рядом с инпутом для хэштегов есть выплывающий список содержащий выбранные хэштеги, при нажатии в этом списке на какой-либо из хэштегов, тот удалится из списка выбранных, и фильтрация по нему проводиться не будет.

**Comment by slawiko** [comment]
Извините, что не ответил. 

То есть фильтрация по хэштегам у вас исключающая и можно исключить только один хэштег?

Не очень хорошая идея составлять фон из картинок, которые не стыкуются незаметно. 

И фильтры устроены очень непонятно. При первом использовании вообще не ясно куда что писать. Нужно как-то их переделать. Можете взять за образец любой фильтр любого вам знакомого сайта.

**Comment by eugeniipol** [comment]
@slawiko Всё поправил, теперь красиво:) С сортировкой стало удобнее, для включения какого-либо из фильтров достаточно поставить галочка в чекбокс напротив него, фильтрация происходит по выбранным хэштегам, что бы прекратить фильтрацию по каком-либо из выбранных хэштегов, нужно нажать на крестик рядом с ним, и он пропадёт из списка.

**Comment by slawiko** [comment]
Стало лучше, но вот я даже читаю ваше объяснение работы фильтра - и всё равно сложно :)

**Comment by slawiko** [comment]
Можете закрывать это ишью
